name: hello
docker_repo: <MYREPO>
docker_bucket: <DOCKER_CFG_BUCKET>
aws_user: <IAM_USER_NAME>
aws_keypair: aws-eb
aws_instance_type: t2.micro
aws_cert_arn: <ARN_OF_SSL_CERTIFICATE>

with_async: true

jwt_issuer: api.helloworld.com
jwt_audience: helloworldaudienceisgreat
jwt_secret: PYM_JWT_SECRET
live_host: helloworld.com

env_secrets:
  - PYM_JWT_SECRET
